setwd("/home/spenn1/PSR_paleo/PSR_data/model_data/")

write.csv(HadpiC_O18, file = "HadpiC_O18.csv", row.names = FALSE)
write.csv(HadpiC_MgCa, file = "HadpiC_MgCa.csv", row.names = FALSE)
write.csv(GISSgCpiC_O18, file = "GISSgCpiC_O18.csv", row.names = FALSE)
write.csv(GISSgCpiC_MgCa, file = "GISSgCpiC_MgCa.csv", row.names = FALSE)
write.csv(GISSgy3piC_O18, file = "GISSgy3piC_O18.csv", row.names = FALSE)
write.csv(GISSgy3piC_MgCa, file = "GISSgy3piC_MgCa.csv", row.names = FALSE)
write.csv(GISSgTckLM_O18, file = "GISSgTckLM_O18.csv", row.names = FALSE)
write.csv(GISSgTckLM_MgCa, file = "GISSgTckLM_MgCa.csv", row.names = FALSE)
write.csv(GISSgTKckLM_O18, file = "GISSgTKckLM_O18.csv", row.names = FALSE)
write.csv(GISSgTKckLM_MgCa, file = "GISSgTKckLM_MgCa.csv", row.names = FALSE)
write.csv(GISSgTcsLM_O18, file = "GISSgTcsLM_O18.csv", row.names = FALSE)
write.csv(GISSgTcsLM_MgCa, file = "GISSgTcsLM_MgCa.csv", row.names = FALSE)

HadpiC_O18<-read.csv(file = "HadpiC_O18.csv")
HadpiC_MgCa<-read.csv(file = "HadpiC_MgCa.csv")
GISSgCpiC_O18<-read.csv(file = "GISSgCpiC_O18.csv")
GISSgCpiC_MgCa<-read.csv(file = "GISSgCpiC_MgCa.csv")
GISSgy3piC_O18<-read.csv(file = "GISSgy3piC_O18.csv")
GISSgy3piC_MgCa<-read.csv(file = "GISSgy3piC_MgCa.csv")
GISSgTckLM_O18<-read.csv(file = "GISSgTckLM_O18.csv")
GISSgTckLM_MgCa<-read.csv(file = "GISSgTckLM_MgCa.csv")
GISSgTKckLM_O18<-read.csv(file = "GISSgTKckLM_O18.csv")
GISSgTKckLM_MgCa<-read.csv(file = "GISSgTKckLM_MgCa.csv")
GISSgTcsLM_O18<-read.csv(file = "GISSgTcsLM_O18.csv")
GISSgTcsLM_MgCa<-read.csv(file = "GISSgTcsLM_MgCa.csv")

